# Generated by Django 5.0 on 2023-12-20 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('st_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('catageory', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('te_id', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=20)),
                ('questions', models.TextField()),
                ('deadline', models.DateField()),
                ('solution', models.TextField(default='NULL')),
                ('marks', models.IntegerField(default=0, max_length=3)),
                ('remarks', models.CharField(default='NULL', max_length=25)),
                ('stu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='st.student')),
            ],
        ),
    ]
